name: emoji_picker_flutter_example
description: Demonstrates how to use the emoji_picker_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.1.0

  emoji_picker_flutter:
    path: ../

dependency_overrides:
  emoji_picker_flutter:
    path: ../

flutter:
  uses-material-design: true
  fonts:
   - family: NotoEmoji
     fonts:  
       - asset: fonts/NotoEmoji-Light.ttf
       - asset: fonts/NotoEmoji-Regular.ttf
       - asset: fonts/NotoEmoji-Medium.ttf
       - asset: fonts/NotoEmoji-SemiBold.ttf
       - asset: fonts/NotoEmoji-Bold.ttf
   - family: NotoColorEmoji
     fonts:  
       - asset: fonts/NotoColorEmoji.ttf
       
       

